dependencies:
  - matplotlib
  - pydub
  - numpy
  - pandas
  - scipy
  - seaborn
  - scikit-learn
  - pip
  - beautifulsoup4
  - librosa
  - glob2
  - keras
  - tensorflow
  - pip:
      - bash_kernel
