dependencies:
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - scikit-learn
  - pip
  - beautifulsoup4
  - librosa
  - glob
  - random
  - sklearn
  - keras
  - tensorflow
  - datetime
  - os
  - pip:
      - bash_kernel
